dataset:
  root: /home/mariapaolagerminario/dataset/behavior1k_training #
  repo_id: behavior-1k/2025-challenge-demos

policy:
  type: pi0
  pretrained_path: lerobot/pi0_base
  device: cuda
  freeze_vision_encoder: True
  train_expert_only: True
  classifier_mode: True
  num_subskill_classes: 8
  n_action_steps: 30
  gradient_checkpointing: True
  use_state: True # If False deactive the state
  
wandb:
  enable: true
  project: pi0-skill-classifier
job_name: pi0-skill-classifier-11_test #

save_checkpoint: true
output_dir: outputs/skill_classifier_test
batch_size: 16
steps: 50000
log_freq: 100
save_freq: 25000
eval_freq: 1000 
seed: 42
resume: false # riaddestra sempre dallo step 0 (perde pesi giá appresi)

# num_workers: 4

mode: train_val_test # options: "train", "train_val", "train_val_test", "test", "inference"
eval_num_batches: 500
test_num_batches: 5000
inference_episodes: [1]



